rd_tlp_axi #(
    DOUBLE_WORD             =        32,
    HEADER_SIZE             =        4*DOUBLE_WORD,
    TLP_DATA_WIDTH          =        8*DOUBLE_WORD,
    AXI_ID_WIDTH            =        8,
    AXI_DATA_WIDTH          =        TLP_DATA_WIDTH,
    AXI_ADDR_WIDTH          =        64,
    AXI_STRB_WIDTH          =        AXI_DATA_WIDTH/8,
    TLP_STRB_WIDTH          =        TLP_DATA_WIDTH/8
)  rd_tlp_axi_ins (
    .clk(clk),
    .rst_n(rst_n),
    .req_tlp_hdr(req_tlp_hdr),
    .req_tlp_sop(req_tlp_sop),
    .req_tlp_eop(req_tlp_eop),
    .req_tlp_valid(req_tlp_valid),
    .req_tlp_ready(req_tlp_ready),
    .cpl_tlp_hdr(cpl_tlp_hdr),
    .cpl_tlp_strb(cpl_tlp_strb),
    .cpl_tlp_data(cpl_tlp_data),
    .cpl_tlp_sop(cpl_tlp_sop),
    .cpl_tlp_eop(cpl_tlp_eop),
    .cpl_tlp_valid(cpl_tlp_valid),
    .cpl_tlp_ready(cpl_tlp_ready),
    .axi_arid(axi_arid),
    .axi_araddr(axi_araddr),
    .axi_arsize(axi_arsize),
    .axi_arlen(axi_arlen),
    .axi_arburst(axi_arburst),
    .axi_arprot(axi_arprot),
    .axi_arlock(axi_arlock),
    .axi_arcache(axi_arcache),
    .axi_arvalid(axi_arvalid),
    .axi_arready(axi_arready),
    .axi_rdata(axi_rdata),
    .axi_rstrb(axi_rstrb),
    .axi_rlast(axi_rlast),
    .axi_rvalid(axi_rvalid),
    .axi_rready(axi_rready),
    .completer_id(completer_id),
    .tlp_error(tlp_error)
);